services:

    email:
        class: Destiny\AppBundle\Services\EmailService
        arguments: ["@swiftmailer.mailer","@templating","@doctrine.orm.entity_manager","@service_container"]

    datosEmpresa:
        class: Destiny\AppBundle\Services\DatosEmpresaService
        arguments: ["@doctrine.orm.entity_manager","@service_container"]

    plantilla:
        class: Destiny\AppBundle\Services\PlantillaService
        arguments: ["@doctrine.orm.entity_manager","@service_container"]

    backend:
        class: Destiny\AppBundle\Services\BackendService
        arguments: ["@doctrine.orm.entity_manager","@service_container","@translator.default"]

    app.permisos_repository:
        class:     Doctrine\ORM\EntityRepository
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Destiny\AppBundle\Entity\BackendPermisos]


    security.access.backend_permisos_voter:
        class:      Destiny\AppBundle\Security\AccessVoter
        public:     false
        arguments: ["@app.permisos_repository"]
        tags:
            - { name: security.voter }

    kernel.listener.modo.mantenimiento.listener:
        class: Destiny\AppBundle\Listener\ModoMantenimientoListener
        arguments: ["@doctrine.orm.entity_manager","@templating","@security.token_storage", "@request_stack"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    destiny_appbundle.form.type.idiomas:
        class:  Destiny\AppBundle\Form\Type\IdiomasType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default"]
        tags:
            - { name: form.type }

    idiomas: "@destiny_appbundle.form.type.idiomas"

    destiny_appbundle.form.type.permisos:
        class:  Destiny\AppBundle\Form\Type\BackendPermisosType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default"]
        tags:
            - { name: form.type }

    backendPermisos: "@destiny_appbundle.form.type.permisos"

    destiny_appbundle.form.type.newsletter:
        class:  Destiny\AppBundle\Form\Type\NewsletterType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default"]
        tags:
            - { name: form.type }

    newsletter: "@destiny_appbundle.form.type.newsletter"

    destiny_appbundle.form.type.mensajes:
        class:  Destiny\AppBundle\Form\Type\MensajesType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default"]
        tags:
            - { name: form.type }

    mensajes: "@destiny_appbundle.form.type.mensajes"

    destiny_appbundle.form.type.contacto:
        class:  Destiny\AppBundle\Form\Type\ContactoType
        arguments: [ "@translator.default"]
        tags:
            - { name: form.type }

    contacto: "@destiny_appbundle.form.type.contacto"

    destiny_appbundle.form.type.usuarios:
        class:  Destiny\AppBundle\Form\Type\UsuariosType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    usuarios: "@destiny_appbundle.form.type.usuarios"

    destiny_appbundle.form.type.usuarios.emails:
        class:  Destiny\AppBundle\Form\Type\UsuariosEmailsType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default"]
        tags:
            - { name: form.type }

    usuariosemails: "@destiny_appbundle.form.type.usuarios.emails"

    destiny_appbundle.form.type.empresa.web:
        class:  Destiny\AppBundle\Form\Type\EmpresaWebType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    empresaWeb: "@destiny_appbundle.form.type.empresa.web"



    destiny_appbundle.form.type.empresa.web.traduccion:
        class:  Destiny\AppBundle\Form\Type\EmpresaWebTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    empresaWeb-traducciones: "@destiny_appbundle.form.type.empresa.web.traduccion"

    destiny_appbundle.form.type.empresa.contacto:
        class:  Destiny\AppBundle\Form\Type\EmpresaContactoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    empresaContacto: "@destiny_appbundle.form.type.empresa.contacto"

    destiny_appbundle.form.type.empresa.redes.sociales:
        class:  Destiny\AppBundle\Form\Type\EmpresaRedesSocialesType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    empresaRedesSociales: "@destiny_appbundle.form.type.empresa.redes.sociales"

    destiny_appbundle.form.type.empresa.emails:
        class:  Destiny\AppBundle\Form\Type\EmpresaEmailsType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default"]
        tags:
            - { name: form.type }

    empresaemails: "@destiny_appbundle.form.type.empresa.emails"

    destiny_appbundle.form.type.adjuntos:
        class:  Destiny\AppBundle\Form\Type\AdjuntosType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    adjuntos: "@destiny_appbundle.form.type.adjuntos"

    destiny_appbundle.form.type.adjuntos.traducciones:
        class:  Destiny\AppBundle\Form\Type\AdjuntosTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    adjuntos-traducciones: "@destiny_appbundle.form.type.adjuntos.traducciones"

    destiny_appbundle.form.type.videos:
        class:  Destiny\AppBundle\Form\Type\VideosType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    videos: "@destiny_appbundle.form.type.videos"

    destiny_appbundle.form.type.videos.traducciones:
        class:  Destiny\AppBundle\Form\Type\VideosTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    videos-traducciones: "@destiny_appbundle.form.type.videos.traducciones"

    destiny_appbundle.form.type.imagenes:
        class:  Destiny\AppBundle\Form\Type\ImagenesType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    imagenes: "@destiny_appbundle.form.type.imagenes"

    destiny_appbundle.form.type.imagenes.traducciones:
        class:  Destiny\AppBundle\Form\Type\ImagenesTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    imagenes-traducciones: "@destiny_appbundle.form.type.imagenes.traducciones"

    destiny_appbundle.form.type.sliders:
        class:  Destiny\AppBundle\Form\Type\SlidersType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    sliders: "@destiny_appbundle.form.type.sliders"

    destiny_appbundle.form.type.sliders.traducciones:
        class:  Destiny\AppBundle\Form\Type\SlidersTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    sliders-traducciones: "@destiny_appbundle.form.type.sliders.traducciones"

    destiny_appbundle.form.type.menu:
        class:  Destiny\AppBundle\Form\Type\MenusType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    menus: "@destiny_appbundle.form.type.menu"

    destiny_appbundle.form.type.secciones:
        class:  Destiny\AppBundle\Form\Type\SeccionesType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    secciones: "@destiny_appbundle.form.type.secciones"

    destiny_appbundle.form.type.grupos.backend:
        class:  Destiny\AppBundle\Form\Type\BackendGruposSeccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    backendgrupossecciones: "@destiny_appbundle.form.type.grupos.backend"

    destiny_appbundle.form.type.menus.backend:
        class:  Destiny\AppBundle\Form\Type\BackendSeccionesType
        arguments: ["@translator.default","@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    backendsecciones: "@destiny_appbundle.form.type.menus.backend"


    destiny_appbundle.form.type.secciones.traduccion:
        class:  Destiny\AppBundle\Form\Type\SeccionesTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    secciones-traducciones: "@destiny_appbundle.form.type.secciones.traduccion"

    destiny_appbundle.form.type.seccionescontenido:
        class:  Destiny\AppBundle\Form\Type\SeccionesContenidoType
        arguments: ["@doctrine.orm.entity_manager","@translator.default"]
        tags:
            - { name: form.type }

    seccionescontenido: "@destiny_appbundle.form.type.seccionescontenido"

    destiny_appbundle.form.type.videoscontenido:
        class:  Destiny\AppBundle\Form\Type\VideosContenidoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    videoscontenido: "@destiny_appbundle.form.type.videoscontenido"

    destiny_appbundle.form.type.imagenescontenido:
        class:  Destiny\AppBundle\Form\Type\ImagenesContenidoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    imagenescontenido: "@destiny_appbundle.form.type.imagenescontenido"

    destiny_appbundle.form.type.sliderscontenido:
        class:  Destiny\AppBundle\Form\Type\SlidersContenidoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    sliderscontenido: "@destiny_appbundle.form.type.sliderscontenido"

    destiny_appbundle.form.type.articuloscontenido:
        class:  Destiny\AppBundle\Form\Type\ArticulosContenidoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    articuloscontenido: "@destiny_appbundle.form.type.articuloscontenido"
    articulos: "@destiny_appbundle.form.type.articuloscontenido"

    destiny_appbundle.form.type.articulos.traducciones:
        class:  Destiny\AppBundle\Form\Type\ArticulosContenidoTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    articulos-traducciones: "@destiny_appbundle.form.type.articulos.traducciones"

    destiny_appbundle.form.type.noticiascategoria:
        class:  Destiny\AppBundle\Form\Type\NoticiasCategoriasType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    noticiascategorias: "@destiny_appbundle.form.type.noticiascategoria"

    destiny_appbundle.form.type.noticiascategoria.traducciones:
        class:  Destiny\AppBundle\Form\Type\NoticiasCategoriasTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    noticiascategorias-traducciones: "@destiny_appbundle.form.type.noticiascategoria.traducciones"

    destiny_appbundle.form.type.noticias:
        class:  Destiny\AppBundle\Form\Type\NoticiasType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    noticias: "@destiny_appbundle.form.type.noticias"

    destiny_appbundle.form.type.noticias.traducciones:
        class:  Destiny\AppBundle\Form\Type\NoticiasTraduccionesType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }

    noticias-traducciones: "@destiny_appbundle.form.type.noticias.traducciones"

    destiny_appbundle.form.type.adjuntoscontenido:
        class:  Destiny\AppBundle\Form\Type\AdjuntosContenidoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    adjuntoscontenido: "@destiny_appbundle.form.type.adjuntoscontenido"

    destiny_appbundle.form.type.noticiascontenido:
        class:  Destiny\AppBundle\Form\Type\NoticiasContenidoType
        arguments: ["@doctrine.orm.entity_manager", "@translator.default","@service_container"]
        tags:
            - { name: form.type }

    noticiascontenido: "@destiny_appbundle.form.type.noticiascontenido"

