<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdjuntosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjuntosRepository extends EntityRepository
{
}
