<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenusBackendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendGruposSeccionesRepository extends EntityRepository
{
	public function getAllByGroup($group)
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder ();

		return $query->select(['s','g'])
			->from('DestinyAppBundle:MenusBackend','s')
			->innerJoin('s.grupo','g')
			->where($query->expr()->eq('g.slug',':grupo'))
			->setParameters([':grupo' => $group,])
			->getQuery()->getResult();


	}
}
