<?php

namespace Destiny\AppBundle\Entity\Repository;

use Destiny\AppBundle\Entity\Usuarios;
use Doctrine\ORM\EntityRepository;

/**
 * BackendSeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendSeccionesRepository extends EntityRepository
{
	public function getActiveMenusBackend(Usuarios $user)
	{
		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder();

        if (!in_array('ROLE_ROOT',$user->getRoles()))
        {
            $consulta =  $query->select(['s','g','p','r'])
                ->from('DestinyAppBundle:BackendGruposSecciones','g')
                ->innerJoin('g.secciones','s')
                ->innerJoin('s.permisos','p')
                ->innerJoin('s.permisos','r')
                ->andWhere($query->expr()->eq('g.estado',':grupo'))
                ->andWhere($query->expr()->eq('s.estado',':seccion'))
                ->andWhere($query->expr()->eq('r.grupo',':rol'))
                ->setParameters([':grupo' => true,'seccion' => true,'rol' => $user->getRoles()[0]]);

            return $consulta->getQuery()->getResult();

        }

        $consulta =  $query->select(['g'])
            ->from('DestinyAppBundle:BackendGruposSecciones','g');

        return $consulta->getQuery()->getResult();

	}

	public function getAllByGroup($group)
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder ();

		return $query->select(['s','g'])
			->from('DestinyAppBundle:BackendSecciones','s')
			->innerJoin('s.grupo','g')
			->where($query->expr()->eq('g.slug',':menu'))
			->setParameters([':menu' => $group,])
			->getQuery()->getResult();


	}

    public function getActiveMenusBackendSuperior()
    {
        $em = $this->getEntityManager ();
        $query = $em->createQueryBuilder();

        $consulta =  $query->select(['s'])
            ->from('DestinyAppBundle:BackendSecciones','s')
            ->where($query->expr()->eq('s.zona',':zona'))
            ->setParameters([':zona' => 'superior'])
        ;

        return $consulta->getQuery()->getResult();
    }
}
