<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BackendSeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendSeccionesRepository extends EntityRepository
{
	public function getActiveMenusBackend($IsRoot = false)
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder();
        if ($IsRoot === false)
        {
            $consulta =  $query->select(['s','g'])
                ->from('DestinyAppBundle:BackendGruposSecciones','g')
                ->innerJoin('g.secciones','s')
                ->where($query->expr()->eq('g.estado',':grupo'))
                ->andWhere($query->expr()->eq('s.estado',':seccion'))
                ->setParameters([':grupo' => true,'seccion' => true]);
        }else {
            $consulta =  $query->select(['s','g'])
                ->from('DestinyAppBundle:BackendGruposSecciones','g')
                ->innerJoin('g.secciones','s')
                ->where($query->expr()->eq('g.estado',':grupo'))
                ->setParameters([':grupo' => true]);
        }

        return $consulta->getQuery()->getResult();


	}

	public function getAllByGroup($group)
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder ();

		return $query->select(['s','g'])
			->from('DestinyAppBundle:BackendSecciones','s')
			->innerJoin('s.grupo','g')
			->where($query->expr()->eq('g.slug',':menu'))
			->setParameters([':menu' => $group,])
			->getQuery()->getResult();


	}
}
