<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BackendSeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendSeccionesRepository extends EntityRepository
{
	public function getActiveMenusBackend()
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder();

		return $query->select(['s','g'])
			->from('DestinyAppBundle:BackendGruposSecciones','g')
			->innerJoin('g.secciones','s')
			->where($query->expr()->eq('g.estado',':grupo'))
			->andWhere($query->expr()->eq('s.estado',':seccion'))
			->setParameters([':grupo' => true,'seccion' => true])
			->getQuery()->getResult();


	}

	public function getAllByGroup($group)
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder ();

		return $query->select(['s','g'])
			->from('DestinyAppBundle:BackendSecciones','s')
			->innerJoin('s.grupo','g')
			->where($query->expr()->eq('g.slug',':menu'))
			->setParameters([':menu' => $group,])
			->getQuery()->getResult();


	}
}
