<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaEmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaEmailsRepository extends EntityRepository
{
	public function getOne()
	{
		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder();

		return $query->select(['e'])
			->from('DestinyAppBundle:EmpresaEmails','e')
			->getQuery()->getOneOrNullResult();
	}
}
