<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiasCategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasCategoriasRepository extends EntityRepository
{
    public function getNoticiasCategoria($categoria)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder();

        return $query->select(['n','nc'])
                    ->from('DestinyAppBundle:Noticias','n')
                    ->innerJoin('n.categorias','nc')
                    ->where($query->expr()->eq('nc.slug',':categoria'))
                    ->andWhere($query->expr()->eq('n.estado',':activada'))
                    ->setParameters([':categoria' => $categoria,':activada' => true])
                    ->getQuery()->getResult()
            ;
    }
}
