<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeccionesContenidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionesContenidoRepository extends EntityRepository
{
	public function getContent($seccion)
	{

		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder();

		return $query->select(['sc','s','m'])
			->from('DestinyAppBundle:SeccionesContenido', 'sc')
			->innerJoin('sc.seccion','s')
			->innerJoin('s.menu','m')
			->where($query->expr()->eq('s.slug',':seccion'))
			->setParameters([':seccion' => $seccion])
            ->orderBy('sc.posicion')
			->getQuery()->getResult();
	}

	public function getOne($slug,$elementType)
	{

		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder ();

		switch($elementType[0]){
			case ($elementType === 'imagenes'):

				return $query->select(['i'])
					->from('DestinyAppBundle:Imagenes', 'i')
					->andWhere($query->expr()->eq('i.slug',':slug'))
					->setParameters([':slug'   => $slug])
					->getQuery()->getOneOrNullResult();
			break;

			case ($elementType === 'videos'):
				return $query->select(['i'])
					->from('DestinyAppBundle:Videos', 'i')
					->andWhere($query->expr()->eq('i.slug',':slug'))
					->setParameters([':slug'   => $slug])
					->getQuery()->getOneOrNullResult();
			break;

			case ($elementType === 'sliders'):
				return $query->select(['i'])
					->from('DestinyAppBundle:Sliders', 'i')
					->andWhere($query->expr()->eq('i.slug',':slug'))
					->setParameters([':slug'   => $slug])
					->getQuery()->getOneOrNullResult();
				break;

			case ($elementType === 'adjuntos'):
				return $query->select(['i'])
					->from('DestinyAppBundle:Adjuntos', 'i')
					->andWhere($query->expr()->eq('i.slug',':slug'))
					->setParameters([':slug'   => $slug])
					->getQuery()->getOneOrNullResult();
				break;

			case ($elementType === 'articulos'):

				return $query->select(['sc'])
					->from('DestinyAppBundle:Articulos', 'sc')
					->andWhere($query->expr()->eq('sc.slug',':slug'))
					->setParameters([':slug' => $slug])
					->getQuery()->getOneOrNullResult();
				break;

            default:
                 return $query->select(['sc','s'])
                            ->from('DestinyAppBundle:SeccionesContenido', 'sc')
                            ->innerJoin('sc.seccion','s')
                            ->leftJoin('sc.videos','v')
                            ->leftJoin('sc.adjuntos','p')
                            ->leftJoin('sc.imagenes','i')
                            ->leftJoin('sc.articulos','a')
                            ->leftJoin('sc.sliders','sl')
                            ->where($query->expr()->eq('s.slug',':slug'))
                            ->andWhere($query->expr()->eq('v.slug',':contenido'))
                            ->orWhere($query->expr()->eq('p.slug',':contenido'))
                            ->orWhere($query->expr()->eq('i.slug',':contenido'))
                            ->orWhere($query->expr()->eq('a.slug',':contenido'))
                            ->orWhere($query->expr()->eq('sl.slug',':contenido'))
                            ->setParameters([':slug' => $elementType, ':contenido' => $slug])
                            ->getQuery()->getOneOrNullResult();


                break;

		}




	}

	public function getChangePosition($contenido,$position)
	{


		$em = $this->getEntityManager ();
		$query = $em->createQueryBuilder();

		return $query->select(['sc','s'])
			->from('DestinyAppBundle:SeccionesContenido','sc')
		    ->innerJoin('sc.seccion','s')
			->where($query->expr()->eq('s.id',':contenido'))
			->andWhere($query->expr()->eq('sc.posicion',':posicion'))
			->setParameters([':contenido'     => $contenido->getSeccion()->getId(),
				':posicion' => $position])
			->getQuery()->getOneOrNullResult();
	}

	public function getAll()
	{


		$em = $this->getEntityManager ();

		$query = $em->createQueryBuilder ();

		return $query->select(['sc'])
			->from('DestinyAppBundle:SeccionesContenido','sc')
			->orderBy('sc.posicion')
			->getQuery()->getResult();
	}
}
