<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlidersTraduccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidersTraduccionesRepository extends EntityRepository
{
	public function getTranslation($seccion,$idioma)
	{
		$em = $this->getEntityManager ();
		$query = $em->createQueryBuilder();

		return $query->select(['st','s','i'])
			->from('DestinyAppBundle:SlidersTraducciones','st')
			->innerJoin('st.canonica','s')
			->innerJoin('st.idioma','i')
			->where($query->expr()->eq('s.slug',':seccion'))
			->andWhere($query->expr()->eq('i.isoCode',':idioma'))
			->setParameters([':seccion' => $seccion,':idioma' => $idioma])
			->getQuery()->getOneOrNullResult();
	}
}
